<?php

namespace FaimfonyBundle\Repository;

/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends \Doctrine\ORM\EntityRepository
{

    public function searchMeal($query)
    {
        return $this->createQueryBuilder('m')
            ->where('m.name LIKE :query')
            ->setParameter('query', $query . '%')
            ->getQuery()
            ->getResult();
    }
}
