<?php

namespace FaimfonyBundle\Repository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends \Doctrine\ORM\EntityRepository
{

//    public function findByUserId($userId)
//    {
//
////        $qb = $this->getEntityManager()->createQueryBuilder();
//        $qb = $this->getEntityManager()->createQueryBuilder();
//
//        $qb->select('u')
//            ->from('\namespace\for\User', 'u')
//            ->join('u.roles', 'r')
//            ->where(...);
//
//        return $qb->getQuery()->getResult();
//
//    }

}
